version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27018:27017  # Host port 27018 mapped to container port 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin_user
      - MONGO_INITDB_ROOT_PASSWORD=secure_password
    volumes:
      - mongodb_data_volume:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8082:8081  # Host port 8082 mapped to container port 8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin_user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secure_password
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongodb_data_volume:
